==============

SELECT * FROM events WHERE answer(description, 'Is this event focused on hanging out and chilling?') = 'Yes' ORDER BY start_time LIMIT 3;
connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "vr_event_hub" does not exist

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1624, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1530, in _execute_and
    all_results, column_info = _execute_structural_sql(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1286, in _execute_structural_sql
    return execute_sql_with_column_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\postgresql_connection.py", line 90, in execute_sql_with_column_info
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "vr_event_hub" does not exist

==============

SELECT * FROM events WHERE answer(description, 'Is this event designed for meeting new friends?') = 'Yes' ORDER BY start_time LIMIT 3;
connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "vr_event_hub" does not exist

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1624, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1530, in _execute_and
    all_results, column_info = _execute_structural_sql(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1286, in _execute_structural_sql
    return execute_sql_with_column_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\postgresql_connection.py", line 90, in execute_sql_with_column_info
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "vr_event_hub" does not exist

==============

SELECT * FROM events WHERE answer(description, 'Is this a chill and hangout event?') = 'Yes' ORDER BY start_time LIMIT 3;
connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "vr_event_hub" does not exist

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1624, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1530, in _execute_and
    all_results, column_info = _execute_structural_sql(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1286, in _execute_structural_sql
    return execute_sql_with_column_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\postgresql_connection.py", line 90, in execute_sql_with_column_info
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "vr_event_hub" does not exist

==============

SELECT * FROM events WHERE answer(description, 'Is this a chill and hangout event?') = 'Yes' ORDER BY start_time LIMIT 5;
HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CF9B86F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
  File "C:\Program Files\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000017CF9B86F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CF9B86F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1624, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1540, in _execute_and
    return _execute_free_text_queries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1405, in _execute_free_text_queries
    _retrieve_and_verify(
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 704, in _retrieve_and_verify
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CF9B86F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
==============

SELECT * FROM events WHERE answer(description, 'Is this an event where I can meet new people?') = 'Yes' AND start_time >= CURRENT_TIMESTAMP ORDER BY start_time LIMIT 5;
HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CF9C03AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
  File "C:\Program Files\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000017CF9C03AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CF9C03AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1605, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1502, in _execute_and
    return _execute_free_text_queries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1405, in _execute_free_text_queries
    _retrieve_and_verify(
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 704, in _retrieve_and_verify
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017CF9C03AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
==============

SELECT * FROM events WHERE answer(description, 'Is this a chill and hangout event?') = 'Yes' ORDER BY start_time LIMIT 3;
HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FECE9272D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
  File "C:\Program Files\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001FECE9272D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FECE9272D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1624, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1540, in _execute_and
    return _execute_free_text_queries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1405, in _execute_free_text_queries
    _retrieve_and_verify(
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 704, in _retrieve_and_verify
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FECE9272D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
==============

SELECT * FROM events WHERE answer(description, 'Is this a chill and hangout event?') = 'Yes' ORDER BY start_time LIMIT 3;
HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001150F9B69D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
  File "C:\Program Files\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001150F9B69D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001150F9B69D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1956, in _suql_execute_single
    visitor(root)
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 236, in __call__
    super().__call__(node)
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\pglast\visitors.py", line 317, in __call__
    result = method(ancestors, node)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 261, in visit_SelectStmt
    results, column_info = _analyze_SelectStmt(
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1624, in _analyze_SelectStmt
    return _execute_and(
           ^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1540, in _execute_and
    return _execute_free_text_queries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 1405, in _execute_free_text_queries
    _retrieve_and_verify(
  File "C:\Users\savan\Downloads\vrchat-guide\packages\suql\src\suql\sql_free_text_support\execute_free_text_sql.py", line 704, in _retrieve_and_verify
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\savan\Downloads\vrchat-guide\.venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001150F9B69D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
